# Generated by Django 4.0.4 on 2022-05-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname']},
        ),
    ]
