# Generated by Django 4.0.4 on 2022-05-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
