# Generated by Django 4.0.4 on 2022-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_contact_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
